### ISSUE TITLE
plugin doesn't work with bootstap3 template

### ISSUE THREAD

**Issue by Poukram35** [SoarinFerret/dokuwiki-plugin-pagebuttons#2]
Hi,
I use the very nice Bootstrap3 template and I was interested in "Page Buttons". I just wanted to point out that the plugin doesn't work at all with this template. 
Adding page and folder are broken, and deleting works but without the confirmation window.
But maybe it's not up to you to fix this, and the author of the template has to make it compatible ? 
Regards

**Comment by annievoss** [comment]
same problem here. When klicking on either button, the start page is displayed bt nothing else happens

**Comment by SoarinFerret** [comment]
Does it work if you enable the usePrompt settting? This enables a JS dialog, helps bypass issues with some templates that have don't support modals

**Comment by Andreas-T** [comment]
Confirming the problem with this template and no it does not work with the usePrompt setting. This setting does not seem to have any effect, no dialog appears.
Tested on Safari 14, I have not tested in other environments.

Edit: The same behaviour is confirmed on Chrome Mac  89.0.4389.90.

**Comment by SoarinFerret** [comment]
@Andreas-T thanks for double-checking that for me. I spun up a container, and I am seeing the same thing. I will hopefully be able to take some time this week to take a look at this

**Comment by Poukram35** [comment]
hi,
I updated pagebuttons plugin on my wiki (with template bootstrap3), and I saw that deleting modal is working, nice ! :)
But add page and folder functions are always broken...
When I try to create a page named "test", if I debug a little bit with Firefox 86.0, it tells me the following : "Navigation to "playground:test&do=edit" prevented due to unknown protocol."
With Chrome 89.0.4389.82, console just tells me "playground:test&do=edit" and it prompt me a modal with the following question: "Open xdg-open ?"

If it can help you...
Thanks for your work

**Comment by Andreas-T** [comment]
I have tested all 3 functions on Safari Mac and Chrome Mac and they all work now. Thank you. I have not tested on Firefox as per the comment from @Poukram35.

Edit: Also tested with or without the usePrompt setting. They both works for me on those browsers.

**Comment by SoarinFerret** [comment]
@Poukram35 Have you tried clearing the cache, and/or re-installing the plugin? This fix is working for me - I have checked with Chromium, Firefox, and Edge (chromium edition).

If that does not work, could you provide a list of additional plugins you have installed? Perhaps another plugin is conflicting with this one

**Comment by Poukram35** [comment]
Hi,
cleared the cache, and/or re-installed the plugin, It's not working for me...
I have many plugins installed, you can see all of them in the attached screenshot.
![Screenshot_2021-03-23 Gestionnaire d'extensions  Preprod INTRANET](https://user-images.githubusercontent.com/5887670/112117955-30933b80-8bbc-11eb-90c5-e5fe995ce612.png)

**Comment by SoarinFerret** [comment]
Wow, yep, that is a lot of plugins - I stopped counting at 40 of them. I feel like it is almost guaranteed its another one of those plugins is somehow causing an issue, and just looking through the list, I can see how a number of them could potentially be causing issues.

My recommendation is to make a complete duplicate of your site, slowly start removing the plugins one by one, until you are able to find the one that is causing issues, then report back here with another issue.
