### ISSUE TITLE
Do not work in Vector template

### ISSUE THREAD

**Issue by mva-klp** [SoarinFerret/dokuwiki-plugin-pagebuttons#5]
Hello! This plugin do not work in  [Vector Template.](https://www.dokuwiki.org/template:vector).

**Comment by eduardomozart** [comment]
Hello,
It's not fault from the plugin itself, the Vector template do not handle MENU_ITEMS_ASSEMBLY so it do not dynamically add items to menu. Please see the section "Add custom plugin tab" from [Vector Template](https://www.dokuwiki.org/template:vector) page to a workaround.

**Comment by SoarinFerret** [comment]
Since this appears to be an issue with the template and not the plugin, I will close for now. Thanks @eduardomozart for guidance on a solution.
